# Generated by Django 4.1 on 2024-05-21 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='issued_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.member'),
        ),
    ]
